services:
  neo4j:
    image: neo4j:5.11.0

    environment:
      - NEO4J_AUTH=${NEO4J_USER}/${NEO4J_PW}
    volumes:
      - neo4j_data:/data
    
    networks:
      backendnetworks:

  stemgraph-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PW=${NEO4J_PW}
      - WRITE_TOKEN=${WRITE_TOKEN}
    depends_on:
      - neo4j

    networks:
      backendnetworks:

volumes:
  neo4j_data:

networks:
  backendnetworks: