services:
  neo4j:
    image: neo4j:5.11.0
    container_name: neo4j
    environment:
      NEO4J_AUTH: "${NEO4J_USER}/${NEO4J_PW}"
    volumes:
      - neo4j_data:/data
    networks:
      - backendnetwork
  
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PW}"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backendnetwork

  stemgraph-api:
    build: .
    container_name: stemgraph-api
    environment:
      NEO4J_URI: "${NEO4J_URI}"
      NEO4J_USER: "${NEO4J_USER}"
      NEO4J_PW: "${NEO4J_PW}"

      WRITE_TOKEN: "${WRITE_TOKEN}"

      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: "5432"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PW}"

    ports:
      - "8000:8000"
    volumes:
      - ../challenges:/challenges
      - ../data:/data
    depends_on:
      - neo4j
      - postgres
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    networks:
      - backendnetwork

volumes:
  neo4j_data:
  postgres_data:

networks:
  backendnetwork:
